no-console: "&czlxqit_ you should know that you can't run this into the console!"
already-connected: "&7&lCHRONIUM: &cYou are already connected to the server's hub!"
success-connect: "&7&lCHRONIUM: &aSuccessfully connected to the server's hub!"